services:
  laravel:
    build:
      context: "./docker/runtimes/8.5"
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
    image: "app-8.5/php"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER:-1000}"
      LARAVEL_SAIL: 1 # mantenha este
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - ".:/var/www/html"
    networks:
      - app-network
      - data-network
    depends_on:
      pgsql:
        condition: service_healthy
      minio:
        condition: service_started

  pgsql:
    image: "postgres:18-alpine"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "app-pgsql:/var/lib/postgresql"
    networks:
      - data-network
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "${DB_DATABASE}"
        - "-U"
        - "${DB_USERNAME}"
      retries: 3
      timeout: 5s

  minio:
    image: "minio/minio:latest"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - "app-minio:/data"
    networks:
      - data-network
    command: 'minio server /data --console-address ":${MINIO_CONSOLE_PORT:-8900}"'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      retries: 3
      timeout: 5s

networks:
  data-network:
    driver: bridge
    external: false

  app-network:
    driver: bridge


volumes:
  app-pgsql:
    driver: local

  app-minio:
    driver: local
